core-deploy:
  enabled: true
  project-modules:
    lwc: lwc.version
branches:
  ~DEFAULT~:
    pull-request: &branch-definition
      auto-start: true
      auto-start-from-forks: false
      merge-method: disabled # do not auto-merge; we'll do it ourselves
      required-downstream-deps:
        - LightningMobileRuntime/ui-lmr-components
        - MobilePlatform/lds-debug-app
        - Trailhead-Platform/ui-trailhead-core-components
        - automation-platform/ui-interaction-explorer-components
        - communities/shared-experience-components
        - communities/ui-feeds-components
        - communities/ui-lightning-community
        - communities/webruntime
        - lwc/lwc-platform
        - nrkruk/lwc-dev-core
        - ris-gpta/core_via_components
        - salesforce/builder-framework
        - salesforce-experience-platform-emu/luvio
        - salesforce-experience-platform-emu/lwr
        - salesforce/lwr-lightning-platform
        - salesforcedevs/doc-framework-monorepo
  release:
    pull-request:
      <<: *branch-definition
      merge-method: force-push # release branch should always be in sync with master branch (linear history)
  spring23:
    pull-request:
      <<: *branch-definition
  summer23:
    pull-request:
      <<: *branch-definition
  winter24:
    pull-request:
      <<: *branch-definition
  milestone-.*: # used for prerelease testing
    pull-request:
      <<: *branch-definition
      workflow: build-and-test # the default workflow is release, and we just want build+tests
steps:
  node-conformance:
    run:
      command: yarn run lint
    after: node-build
  node-unit-tests:
    run:
      command: yarn test
  # this project runs yarn build after yarn install so skip explicit build step
  node-build: &node-build
    skip: true
  node-pre-release-tests:
    params:
      command: yarn test
  npm-configure:
    params:
      registry-url: https://registry.yarnpkg.com
  npm-configure-for-publish:
    params:
      registry-url: https://registry.npmjs.org
  node-save-dep-cache: &node-save-dep-cache
    params:
      paths:
        # it's necessary to redeclare **/node_modules because this overrides the default behavior
        - '**/node_modules'
        # add NX cache
        - '.nx-cache'
    after: node-build
  npm-publish-release:
    params:
      access: public
      tag: latest # note: this should be summer22, winter23, etc. if this .nucleus.yaml file is in a non-master branch
