core-deploy:
  enabled: true
  project-modules:
    lwc: lwc.version
branches:
  ~DEFAULT~:
    pull-request:
      auto-start: true
      auto-start-from-forks: false
      required-downstream-deps:
        - lwc/lwc-platform
        - salesforce/luvio
        - salesforce/lwr
