core-deploy:
    enabled: true
    project-modules:
        lwc: lwc.version
branches:
    ~DEFAULT~:
        pull-request: &branch-definition
            auto-start: true
            auto-start-from-forks: false
            merge-method: disabled # do not auto-merge; we'll do it ourselves
            required-downstream-deps:
                - BuilderFramework/builder-framework-salesforce
                - MobilePlatform/lsdk-modules
                - MobilePlatform/lwr-lightning-platform
                - MobilePlatform/ui-fsm-components
                - Skilling-and-Enablement/storybook-utils
                - Skilling-and-Enablement/ui-external-enablement
                - automation-platform/ui-externalservices-builder-components
                - automation-platform/ui-interaction-explorer-components
                - communities/microsite-template-marketing
                - communities/shared-experience-components
                - communities/ui-commerce-components
                - communities/webruntime
                - lds/lds-plugins
                - salesforce-experience-platform-emu/komaci
                - salesforce-experience-platform-emu/locker-pentest-app
                - salesforce-experience-platform-emu/lwr
                - salesforce-experience-platform-emu/lwr-everywhere
                - salesforce-experience-platform-emu/lwr-recipes
                - salesforce/lwc-test
                - salesforce/o11y-sample-app
    release:
        pull-request:
            <<: *branch-definition
            merge-method: force-push # release branch should always be in sync with master branch (linear history)
    spring24:
        pull-request:
            <<: *branch-definition
    summer24:
        pull-request:
            <<: *branch-definition
jobs:
    build-and-test:
        memory-limit: 16
    create-canary-release:
        memory-limit: 16
    build-dependency:
        memory-limit: 16
    release:
        memory-limit: 16
steps:
    node-conformance:
        run:
            command: yarn run lint
        after: node-build
    node-unit-tests:
        run:
            command: yarn test
    # this project runs yarn build after yarn install so skip explicit build step
    node-build: &node-build
        skip: true
    node-pre-release-tests:
        params:
            command: yarn test
    npm-configure:
        params:
            registry-url: https://registry.yarnpkg.com
    npm-configure-for-publish:
        params:
            registry-url: https://registry.npmjs.org
    npm-publish-release:
        params:
            access: public
            tag: latest # note: this should be summer22, winter23, etc. if this .nucleus.yaml file is in a non-master branch
