core-deploy:
  enabled: true
  project-modules:
    lwc: lwc.version
branches:
  ~DEFAULT~:
    pull-request: &branch-definition
      auto-start: true
      auto-start-from-forks: false
      merge-method: disabled # do not auto-merge; we'll do it ourselves
      required-downstream-deps:
        - communities/shared-experience-components
        - communities/ui-b2b-components
        - communities/ui-lightning-community
        - salesforce/lwr
        - salesforce/utam-docs
        - uiplatform/nucleus
  release:
    pull-request:
      <<: *branch-definition
      merge-method: force-push # release branch should always be in sync with master branch (linear history)
  spring22:
    pull-request:
      <<: *branch-definition
  summer22:
    pull-request:
      <<: *branch-definition
steps:
  node-conformance:
    run:
      command: yarn run lint
    after: node-build
  node-unit-tests:
    run:
      command: yarn test
  # this project runs yarn build after yarn install so skip explicit build step
  node-build: &node-build
    skip: true
  node-pre-release-tests:
    params:
      command: yarn test
  npm-configure:
    params:
      registry-url: https://registry.yarnpkg.com
  npm-configure-for-publish:
    params:
      registry-url: https://registry.npmjs.org
  npm-publish-release:
    params:
      access: public
      tag: winter23
