core-deploy:
    enabled: true
    project-modules:
        lwc: lwc.version
branches:
    ~DEFAULT~:
        pull-request: &branch-definition
            workflow: build-and-test
            auto-start: true
            auto-start-from-forks: false
            merge-method: disabled # do not auto-merge; we'll do it ourselves
            required-downstream-deps:
                - BuilderFramework/builder-framework-salesforce
                - MobilePlatform/lsdk-modules
                - MobilePlatform/lwr-lightning-platform
                - MobilePlatform/ui-fsm-components
                - automation-platform/ui-externalservices-builder-components
                - communities/microsite-template-marketing
                - communities/shared-experience-components
                - communities/ui-commerce-components
                - communities/webruntime
                - lds/lds-plugins
                - salesforce-experience-platform-emu/komaci
                - salesforce-experience-platform-emu/locker-pentest-app
                - salesforce-experience-platform-emu/lwr
                - salesforce-experience-platform-emu/lwr-everywhere
                - salesforce-experience-platform-emu/lwr-recipes
                - salesforce/lwc-test
                # Using old major versions; tests in PRs will always fail
                # - salesforce/o11y-sample-app
                # - Skilling-and-Enablement/ui-external-enablement
    release:
        pull-request:
            <<: *branch-definition
    # Only active branches need to be included in this config
    winter26:
        pull-request:
            <<: *branch-definition
    spring25:
        pull-request:
            <<: *branch-definition
    summer25:
        pull-request:
            <<: *branch-definition
jobs:
    build-and-test:
        memory-limit: 16
    create-canary-release:
        memory-limit: 16
    build-dependency:
        memory-limit: 16
    release:
        memory-limit: 16
steps:
    node-conformance:
        run:
            command: yarn run lint
        after: node-build
    node-unit-tests:
        run:
            command: yarn test
    # this project runs yarn build after yarn install so skip explicit build step
    node-build: &node-build
        skip: true
