# shared config. The `__shared_config__` name isn't meaningful.
__shared_config__: &branch-definition
  auto-start: true
  auto-start-from-forks: false
  required-downstream-deps:
    - automation-platform/ui-interaction-explorer-components
    - communities/microsite-template-marketing
    - communities/shared-experience-components
    - communities/ui-b2b-components
    - communities/ui-cms-components
    - communities/ui-feeds-components
    - communities/ui-lightning-community
    - lwc/lwc-platform
    - salesforce/lds-lightning-platform
    - salesforce/luvio
    - salesforce/lwr
    - salesforce/lwr-recipes
    - salesforce/utam-docs
    - salesforcedevs/developer-website
    - uiplatform/nucleus
core-deploy:
  enabled: true
  project-modules:
    lwc: lwc.version
branches:
  ~DEFAULT~:
    pull-request:
      <<: *branch-definition
      merge-method: disabled # do not auto-merge; we'll do it ourselves
  release:
    pull-request:
      <<: *branch-definition
      merge-method: force-push # release branch should always be in sync with master branch (linear history)
  winter22:
    pull-request:
      <<: *branch-definition
      merge-method: disabled # do not auto-merge; we'll do it ourselves
  spring22:
    pull-request:
      <<: *branch-definition
      merge-method: disabled # do not auto-merge; we'll do it ourselves
steps:
  node-conformance:
    run:
      command: yarn run lint
    after: node-build
  node-unit-tests:
    run:
      command: yarn test
  # this project runs yarn build after yarn install so skip explicit build step
  node-build: &node-build
    skip: true
  node-pre-release-tests:
    params:
      command: yarn test
  npm-configure:
    params:
      registry-url: https://registry.yarnpkg.com
  npm-configure-for-publish:
    params:
      registry-url: https://registry.npmjs.org
