core-deploy:
    enabled: true
    project-modules:
        lwc: lwc.version
branches:
    ~DEFAULT~:
        pull-request: &branch-definition
            workflow: build-and-test
            auto-start: true
            auto-start-from-forks: false
            merge-method: disabled # do not auto-merge; we'll do it ourselves
            required-downstream-deps:
                # none
    release:
        pull-request:
            <<: *branch-definition
    # Only active branches need to be included in this config
    winter26:
        pull-request:
            <<: *branch-definition
    spring25:
        pull-request:
            <<: *branch-definition
    summer25:
        pull-request:
            <<: *branch-definition
jobs:
    build-and-test:
        memory-limit: 16
    create-canary-release:
        memory-limit: 16
    build-dependency:
        memory-limit: 16
    release:
        memory-limit: 16
steps:
    node-conformance:
        run:
            command: yarn run lint
        after: node-build
    node-unit-tests:
        run:
            command: yarn test
    # this project runs yarn build after yarn install so skip explicit build step
    node-build: &node-build
        skip: true
