global:
    email-reply-to: raptorteam@salesforce.com
    preprocessor-tag: jenkins-sfci-sfci-managed-preprocessor-PR-6322-latest-itest
    production-branches:
        - master
stages:
    build:
        - npm-setup:
              name: yarn-validation
              image: docker.repo.local.sfdc.net/sfci/docker-images/sfdc_rhel9_nodejs18/sfdc_rhel9_nodejs18_build:latest
              commands:
                  - yarn
                  - yarn test:ci
    integration-test:
        - downstream-dependency:
              downstream-repos:
                  - repo-url: https://github.com/salesforce-experience-platform-emu/lwc-platform
                    branches:
                        - main
