/*
 * Copyright (c) 2026, Salesforce, Inc.
 * All rights reserved.
 * SPDX-License-Identifier: MIT
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/MIT
 */

const registeredTemplates = new WeakSet<object>();

/**
 * Marks a template as having been generated by the compiler
 * @param tmpl the compiled template function to register
 * @returns the same template function, for chaining with an assignment
 * @internal
 */
export function registerTemplate<T extends object>(tmpl: T): T {
    registeredTemplates.add(tmpl);
    return tmpl;
}

export function isTemplateRegistered(tmpl: unknown): boolean {
    if (tmpl === null || (typeof tmpl !== 'function' && typeof tmpl !== 'object')) {
        return false;
    }
    return registeredTemplates.has(tmpl);
}
