import { API_VERSION } from './options.mjs';

// These values are based on the API versions in @lwc/shared/api-version
export const LOWERCASE_SCOPE_TOKENS = API_VERSION >= 59,
    USE_COMMENTS_FOR_FRAGMENT_BOOKENDS = API_VERSION >= 60,
    USE_FRAGMENTS_FOR_LIGHT_DOM_SLOTS = API_VERSION >= 60,
    DISABLE_OBJECT_REST_SPREAD_TRANSFORMATION = API_VERSION >= 60,
    ENABLE_ELEMENT_INTERNALS_AND_FACE = API_VERSION >= 61,
    USE_LIGHT_DOM_SLOT_FORWARDING = API_VERSION >= 61,
    ENABLE_THIS_DOT_HOST_ELEMENT = API_VERSION >= 62,
    ENABLE_THIS_DOT_STYLE = API_VERSION >= 62,
    TEMPLATE_CLASS_NAME_OBJECT_BINDING = API_VERSION >= 62;

export const IS_SYNTHETIC_SHADOW_LOADED = !`${ShadowRoot}`.includes('[native code]');
