/*
 * Copyright (c) 2024, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: MIT
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/MIT
 */
import { is } from 'estree-toolkit';
import { isUndefined } from '@lwc/shared';
import { expressionIrToEs } from '../../expression';
import { esTemplateWithYield } from '../../../estemplate';
import { getChildAttrsOrProps } from '../../shared';
import { getSlottedContent } from './slotted-content';
import type { Transformer } from '../../types';
import type {
    LwcComponent as IrLwcComponent,
    Expression as IrExpression,
} from '@lwc/template-compiler';
import type { Statement as EsStatement } from 'estree';

// Note that `slottedContent` is the name of the variable used to store the slotted content
// generated by getSlottedContent.
const bYieldFromDynamicComponentConstructorGenerator = esTemplateWithYield`
    const Ctor = '${/* lwcIs attribute value */ is.expression}';
    if (Ctor) {
        if (typeof Ctor !== 'function' || !(Ctor.prototype instanceof LightningElement)) {
            throw new Error(\`Invalid constructor: "\${String(Ctor)}" is not a LightningElement constructor.\`)
        }
        const childProps = __getReadOnlyProxy(${/* child props */ is.objectExpression});
        const childAttrs = ${/* child attrs */ is.objectExpression};
        ${/* slotted content */ is.statement}

        const scopeToken = hasScopedStylesheets ? stylesheetScopeToken : undefined;

        yield* Ctor[SYMBOL__GENERATE_MARKUP](
            null, 
            childProps,
            childAttrs,
            slottedContent,
            scopeToken
        );
    }
`<EsStatement[]>;

export const LwcComponent: Transformer<IrLwcComponent> = function LwcComponent(node, cxt) {
    const { directives } = node;

    const lwcIs = directives.find((directive) => directive.name === 'Is');
    if (!isUndefined(lwcIs)) {
        cxt.import({
            getReadOnlyProxy: '__getReadOnlyProxy',
            LightningElement: undefined,
            SYMBOL__GENERATE_MARKUP: undefined,
        });

        return bYieldFromDynamicComponentConstructorGenerator(
            expressionIrToEs(lwcIs.value as IrExpression, cxt),
            getChildAttrsOrProps(node.properties, cxt),
            getChildAttrsOrProps(node.attributes, cxt),
            getSlottedContent(node, cxt)
        );
    } else {
        return [];
    }
};
