export const mockState = {
    flatRecord: {
        id: '006xx000001ZdxuAAC',
        values: {
            Account: {
                apiName: 'Account',
                childRelationships: {},
                fields: {
                    Id: {
                        displayValue: null,
                        value: '001xx000003DIIxAAO',
                    },
                    Name: {
                        displayValue: null,
                        value: 'Acme',
                    },
                },
                id: '001xx000003DIIxAAO',
                recordTypeInfo: null,
            },
            AccountId: '001xx000003DIIxAAO',
            Amount: 140000,
            Campaign: null,
            CampaignId: null,
            Checkbox10__c: false,
            Checkbox11__c: false,
            Checkbox12__c: false,
            Checkbox13__c: false,
            Checkbox14__c: false,
            Checkbox15__c: false,
            Checkbox16__c: false,
            Checkbox17__c: false,
            Checkbox18__c: false,
            Checkbox19__c: false,
            Checkbox1__c: true,
            Checkbox20__c: false,
            Checkbox2__c: false,
            Checkbox3__c: false,
            Checkbox4__c: true,
            Checkbox5__c: false,
            Checkbox6__c: false,
            Checkbox7__c: false,
            Checkbox8__c: false,
            Checkbox9__c: false,
            CloseDate: '2015-05-05',
            CreatedBy: {
                apiName: 'User',
                childRelationships: {},
                fields: {
                    Id: {
                        displayValue: null,
                        value: '005xx000001T1vNAAS',
                    },
                    Name: {
                        displayValue: null,
                        value: 'Test User',
                    },
                },
                id: '005xx000001T1vNAAS',
                recordTypeInfo: null,
            },
            CreatedById: '005xx000001T1vNAAS',
            CreatedDate: '2017-07-17T20:36:53.000Z',
            Currency10__c: 765,
            Currency11__c: 765,
            Currency12__c: 43,
            Currency13__c: 6,
            Currency14__c: 7876,
            Currency15__c: 45,
            Currency16__c: 4,
            Currency17__c: 87,
            Currency18__c: 234,
            Currency19__c: 876,
            Currency1__c: 876,
            Currency20__c: 6,
            Currency2__c: 899,
            Currency3__c: 98,
            Currency4__c: 98,
            Currency5__c: 5,
            Currency7__c: 456,
            Currency8__c: 88,
            Currency9__c: 87,
            Date10__c: null,
            Date11__c: null,
            Date12__c: null,
            Date13__c: null,
            Date14__c: null,
            Date15__c: null,
            Date16__c: null,
            Date17__c: null,
            Date18__c: null,
            Date19__c: null,
            Date1__c: '2017-07-31',
            Date20__c: null,
            Date5__c: null,
            Date6__c: null,
            Date7__c: null,
            Date8__c: null,
            Date9__c: null,
            DateTime10__c: '2017-07-18T19:30:00.000Z',
            DateTime11__c: '2017-07-03T19:30:00.000Z',
            DateTime12__c: '2017-07-19T19:30:00.000Z',
            DateTime13__c: null,
            DateTime14__c: '2017-07-05T19:30:00.000Z',
            DateTime15__c: '2017-07-17T19:30:00.000Z',
            DateTime16__c: null,
            DateTime17__c: '2017-07-02T19:30:00.000Z',
            DateTime18__c: null,
            DateTime19__c: '2017-07-04T19:30:00.000Z',
            DateTime1__c: '2017-07-11T19:30:00.000Z',
            DateTime20__c: null,
            DateTime2__c: null,
            DateTime3__c: '2017-07-03T19:30:00.000Z',
            DateTime4__c: null,
            DateTime5__c: null,
            DateTime6__c: null,
            DateTime7__c: null,
            DateTime8__c: null,
            DateTime9__c: null,
            Description:
                'The deal is at  50% because they are at the sales process stage of evaluating our ROI justification.',
            Email10__c: 'foo@bar.com',
            Email11__c: 'foo@bar.com',
            Email12__c: 'foo@bar.com',
            Email13__c: 'foo@bar.com',
            Email14__c: 'foo@bar.com',
            Email15__c: 'foo@bar.com',
            Email16__c: 'foo@bar.com',
            Email17__c: 'foo@bar.com',
            Email18__c: 'foo@bar.com',
            Email19__c: 'foo@bar.comv',
            Email1__c: 'foo@bar.com',
            Email20__c: 'foo@bar.com',
            Email2__c: 'foo@bar.com',
            Email3__c: 'foo@bar.com',
            Email4__c: 'foo@bar.com',
            Email5__c: 'foo@bar.com',
            Email6__c: 'foo@bar.com',
            Email7__c: 'foo@bar.com',
            Email8__c: 'foo@bar.com',
            Email9__c: 'foo@bar.com',
            ForecastCategoryName: 'Pipeline',
            LastModifiedBy: {
                apiName: 'User',
                childRelationships: {},
                fields: {
                    Id: {
                        displayValue: null,
                        value: '005xx000001T1vNAAS',
                    },
                    Name: {
                        displayValue: null,
                        value: 'Test User',
                    },
                },
                id: '005xx000001T1vNAAS',
                recordTypeInfo: null,
            },
            LastModifiedById: '005xx000001T1vNAAS',
            LastModifiedDate: '2017-07-21T19:32:11.000Z',
            LeadSource: 'Trade Show',
            Name: 'Acme - 1,200 Widgets',
            NextStep: 'Need estimate',
            Num10__c: 876,
            Num11__c: 87,
            Num12__c: 65,
            Num13__c: 68,
            Num14__c: 876,
            Num15__c: 123,
            Num16__c: 765,
            Num17__c: 65,
            Num18__c: null,
            Num19__c: null,
            Num1__c: 76,
            Num20__c: 5,
            Num2__c: 87,
            Num3__c: 876,
            Num4__c: 876,
            Num5__c: 5,
            Num6__c: 5,
            Num7__c: 7865,
            Num8__c: 7865,
            Num9__c: 86,
            Owner: {
                apiName: 'User',
                childRelationships: {},
                fields: {
                    Id: {
                        displayValue: null,
                        value: '005xx000001T1vNAAS',
                    },
                    Name: {
                        displayValue: null,
                        value: 'Test User',
                    },
                },
                id: '005xx000001T1vNAAS',
                recordTypeInfo: null,
            },
            OwnerId: '005xx000001T1vNAAS',
            Perc10__c: 4,
            Perc11__c: 6,
            Perc12__c: 123,
            Perc13__c: 123,
            Perc14__c: 5,
            Perc15__c: 6,
            Perc16__c: 123,
            Perc17__c: 123,
            Perc18__c: 5,
            Perc19__c: 8,
            Perc1__c: 122,
            Perc20__c: 2,
            Perc2__c: 2,
            Perc3__c: 9,
            Perc4__c: 9,
            Perc5__c: 6,
            Perc6__c: 7,
            Perc7__c: 7,
            Perc8__c: 6,
            Perc9__c: 5,
            Phone11__c: '65',
            Phone12__c: '87',
            Phone13__c: '876',
            Phone14__c: '587',
            Phone15__c: '5',
            Phone16__c: '876',
            Phone17__c: '65',
            Phone18__c: '8765',
            Phone19__c: '876',
            Phone20__c: '876',
            Phone2__c: '5',
            Phone3__c: '765',
            Phone4__c: '58',
            Phone5__c: '587',
            Phone6__c: '876',
            Phone7__c: '765',
            Phone8__c: '65',
            Phone9__c: '876',
            Pricebook2: null,
            Pricebook2Id: null,
            Probability: 50,
            StageName: 'Value Proposition',
            Text18__c: 'foo',
            Text19__c: 'gkj',
            Text1__c: 'is',
            Text20__c: 'hjg',
            Text2__c: 'garbage',
            Text3__c: 'stuff',
            Text4__c: 'for',
            Text5__c: 'recprd',
            Text8__c: 'kjh',
            Text9__c: 'hg',
            TextArea10__c: 'kgv',
            TextArea11__c: 'hg',
            TextArea12__c: 'kj',
            TextArea13__c: 'jkh',
            TextArea14__c: 'kj',
            TextArea15__c: 'gkj',
            TextArea16__c: 'hg',
            TextArea17__c: 'hj',
            TextArea18__c: 'kjhg',
            TextArea19__c: 'hg',
            TextArea1__c: 'asd',
            TextArea20__c: 'kj',
            TextArea2__c: 'vh',
            TextArea3__c: 'kjh',
            TextArea4__c: 'gv',
            TextArea5__c: 'hg',
            TextArea6__c: 'kjh',
            TextArea7__c: 'khg',
            TextArea8__c: 'gkj',
            TextArea9__c: 'jgv',
            Type: 'Existing Business',
            c01__c: 12,
            c02__c: 123,
            c03__c: 123,
            c04__c: 123,
            c05__c: '2017-07-02',
            date01__c: '2017-07-15',
            date02__c: '2017-07-03',
            date03__c: '2017-07-10',
            date04__c: '2017-07-10',
            date05__c: '2017-07-03',
            dt01__c: '2017-07-13T22:17:00.000Z',
            dt02__c: '2017-07-04T22:17:00.000Z',
            dt03__c: '2017-07-20T22:17:00.000Z',
            dt04__c: '2017-06-28T22:17:00.000Z',
            dt05__c: '2017-07-07T22:17:00.000Z',
            dt06__c: '2017-07-22T22:17:00.000Z',
            dt07__c: '2017-07-16T22:17:00.000Z',
            dt08__c: '2017-07-04T01:42:00.000Z',
            dt09__c: '2017-06-27T01:42:00.000Z',
            dt10__c: '2017-07-10T22:17:00.000Z',
            e01__c: 'foo@bar.com',
            e02__c: 'foo@bar.com',
            e03__c: 'foo@bar.com',
            e04__c: 'foo@bar.com',
            e05__c: 'foo@bar.com',
            e06__c: 'foo@bar.com',
            e07__c: 'foo@bar.com',
            e08__c: 'foo@bar.com',
            e09__c: 'foo@bar.com',
            e10__c: 'foo@bar.com',
            n01__c: 123,
            n02__c: 120,
            n03__c: 786234876,
            n04__c: 387623,
            n05__c: 28765,
            n06__c: 123213423,
            n07__c: 23423234,
            n08__c: 12457,
            n09__c: 245769,
            n10__c: 234275,
            percent01__c: 12,
            percent02__c: 345,
            percent03__c: 12,
            percent04__c: 345,
            percent05__c: 23,
            percent06__c: 123,
            percent07__c: 2,
            percent09__c: 123,
            percent8__c: 3,
            phone01__c: '34',
            phone02__c: '5',
            phone03__c: '55',
            phone04__c: '123',
            phone05__c: '35',
            phone06__c: '1234',
            phone07__c: '54',
            phone08__c: '123',
            phone09__c: '32',
            phone10__c: 's2e234',
            picklist02__c: 't01,t02,t03,t04,t01,t02,t03,t04,t01,t02,t03,t04',
            picklist03__c: 'b',
            picklist04__c: 'a',
            picklist__c: 'pick01,pick02,pick03',
            rt01__c:
                '&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;',
            rt02__c:
                '&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;',
            txt01__c: 'asd',
            txt02__c: 'sdf',
            txt03__c: 'sdf',
            txt04__c: 'sdf',
            txt05__c: 'sdf',
            txt06__c: 'sdf',
            txt07__c: 'sdf',
            txt08__c: 'sdf',
            txt09__c: 'sdf',
            txt10__c: 'dsfsdf',
            url01__c: 'foo.com',
            url02__c: 'qsd',
        },
        displayValues: {
            Account: 'Acme',
            AccountId: null,
            Amount: '$140,000.00',
            Campaign: null,
            CampaignId: null,
            Checkbox10__c: null,
            Checkbox11__c: null,
            Checkbox12__c: null,
            Checkbox13__c: null,
            Checkbox14__c: null,
            Checkbox15__c: null,
            Checkbox16__c: null,
            Checkbox17__c: null,
            Checkbox18__c: null,
            Checkbox19__c: null,
            Checkbox1__c: null,
            Checkbox20__c: null,
            Checkbox2__c: null,
            Checkbox3__c: null,
            Checkbox4__c: null,
            Checkbox5__c: null,
            Checkbox6__c: null,
            Checkbox7__c: null,
            Checkbox8__c: null,
            Checkbox9__c: null,
            CloseDate: '5/5/2015',
            CreatedBy: 'Test User',
            CreatedById: null,
            CreatedDate: '7/17/2017 1:36 PM',
            Currency10__c: '$765',
            Currency11__c: '$765',
            Currency12__c: '$43',
            Currency13__c: '$6',
            Currency14__c: '$7,876',
            Currency15__c: '$45',
            Currency16__c: '$4',
            Currency17__c: '$87',
            Currency18__c: '$234',
            Currency19__c: '$876',
            Currency1__c: '$876',
            Currency20__c: '$6',
            Currency2__c: '$899',
            Currency3__c: '$98',
            Currency4__c: '$98',
            Currency5__c: '$5',
            Currency7__c: '$456',
            Currency8__c: '$88',
            Currency9__c: '$87',
            Date10__c: null,
            Date11__c: null,
            Date12__c: null,
            Date13__c: null,
            Date14__c: null,
            Date15__c: null,
            Date16__c: null,
            Date17__c: null,
            Date18__c: null,
            Date19__c: null,
            Date1__c: '7/31/2017',
            Date20__c: null,
            Date5__c: null,
            Date6__c: null,
            Date7__c: null,
            Date8__c: null,
            Date9__c: null,
            DateTime10__c: '7/18/2017 12:30 PM',
            DateTime11__c: '7/3/2017 12:30 PM',
            DateTime12__c: '7/19/2017 12:30 PM',
            DateTime13__c: null,
            DateTime14__c: '7/5/2017 12:30 PM',
            DateTime15__c: '7/17/2017 12:30 PM',
            DateTime16__c: null,
            DateTime17__c: '7/2/2017 12:30 PM',
            DateTime18__c: null,
            DateTime19__c: '7/4/2017 12:30 PM',
            DateTime1__c: '7/11/2017 12:30 PM',
            DateTime20__c: null,
            DateTime2__c: null,
            DateTime3__c: '7/3/2017 12:30 PM',
            DateTime4__c: null,
            DateTime5__c: null,
            DateTime6__c: null,
            DateTime7__c: null,
            DateTime8__c: null,
            DateTime9__c: null,
            Description: null,
            Email10__c: null,
            Email11__c: null,
            Email12__c: null,
            Email13__c: null,
            Email14__c: null,
            Email15__c: null,
            Email16__c: null,
            Email17__c: null,
            Email18__c: null,
            Email19__c: null,
            Email1__c: null,
            Email20__c: null,
            Email2__c: null,
            Email3__c: null,
            Email4__c: null,
            Email5__c: null,
            Email6__c: null,
            Email7__c: null,
            Email8__c: null,
            Email9__c: null,
            ForecastCategoryName: 'Pipeline',
            LastModifiedBy: 'Test User',
            LastModifiedById: null,
            LastModifiedDate: '7/21/2017 12:32 PM',
            LeadSource: 'Trade Show',
            Name: null,
            NextStep: null,
            Num10__c: null,
            Num11__c: null,
            Num12__c: null,
            Num13__c: null,
            Num14__c: null,
            Num15__c: null,
            Num16__c: null,
            Num17__c: null,
            Num18__c: null,
            Num19__c: null,
            Num1__c: null,
            Num20__c: null,
            Num2__c: null,
            Num3__c: null,
            Num4__c: null,
            Num5__c: null,
            Num6__c: null,
            Num7__c: null,
            Num8__c: null,
            Num9__c: null,
            Owner: 'Test User',
            OwnerId: null,
            Perc10__c: null,
            Perc11__c: null,
            Perc12__c: null,
            Perc13__c: null,
            Perc14__c: null,
            Perc15__c: null,
            Perc16__c: null,
            Perc17__c: null,
            Perc18__c: null,
            Perc19__c: null,
            Perc1__c: null,
            Perc20__c: null,
            Perc2__c: null,
            Perc3__c: null,
            Perc4__c: null,
            Perc5__c: null,
            Perc6__c: null,
            Perc7__c: null,
            Perc8__c: null,
            Perc9__c: null,
            Phone11__c: null,
            Phone12__c: null,
            Phone13__c: null,
            Phone14__c: null,
            Phone15__c: null,
            Phone16__c: null,
            Phone17__c: null,
            Phone18__c: null,
            Phone19__c: null,
            Phone20__c: null,
            Phone2__c: null,
            Phone3__c: null,
            Phone4__c: null,
            Phone5__c: null,
            Phone6__c: null,
            Phone7__c: null,
            Phone8__c: null,
            Phone9__c: null,
            Pricebook2: null,
            Pricebook2Id: null,
            Probability: null,
            StageName: 'Value Proposition',
            Text18__c: null,
            Text19__c: null,
            Text1__c: null,
            Text20__c: null,
            Text2__c: null,
            Text3__c: null,
            Text4__c: null,
            Text5__c: null,
            Text8__c: null,
            Text9__c: null,
            TextArea10__c: null,
            TextArea11__c: null,
            TextArea12__c: null,
            TextArea13__c: null,
            TextArea14__c: null,
            TextArea15__c: null,
            TextArea16__c: null,
            TextArea17__c: null,
            TextArea18__c: null,
            TextArea19__c: null,
            TextArea1__c: null,
            TextArea20__c: null,
            TextArea2__c: null,
            TextArea3__c: null,
            TextArea4__c: null,
            TextArea5__c: null,
            TextArea6__c: null,
            TextArea7__c: null,
            TextArea8__c: null,
            TextArea9__c: null,
            Type: 'Existing Business',
            c01__c: '$12',
            c02__c: '$123',
            c03__c: '$123',
            c04__c: '$123',
            c05__c: '7/2/2017',
            date01__c: '7/15/2017',
            date02__c: '7/3/2017',
            date03__c: '7/10/2017',
            date04__c: '7/10/2017',
            date05__c: '7/3/2017',
            dt01__c: '7/13/2017 3:17 PM',
            dt02__c: '7/4/2017 3:17 PM',
            dt03__c: '7/20/2017 3:17 PM',
            dt04__c: '6/28/2017 3:17 PM',
            dt05__c: '7/7/2017 3:17 PM',
            dt06__c: '7/22/2017 3:17 PM',
            dt07__c: '7/16/2017 3:17 PM',
            dt08__c: '7/3/2017 6:42 PM',
            dt09__c: '6/26/2017 6:42 PM',
            dt10__c: '7/10/2017 3:17 PM',
            e01__c: null,
            e02__c: null,
            e03__c: null,
            e04__c: null,
            e05__c: null,
            e06__c: null,
            e07__c: null,
            e08__c: null,
            e09__c: null,
            e10__c: null,
            n01__c: null,
            n02__c: null,
            n03__c: null,
            n04__c: null,
            n05__c: null,
            n06__c: null,
            n07__c: null,
            n08__c: null,
            n09__c: null,
            n10__c: null,
            percent01__c: null,
            percent02__c: null,
            percent03__c: null,
            percent04__c: null,
            percent05__c: null,
            percent06__c: null,
            percent07__c: null,
            percent09__c: null,
            percent8__c: null,
            phone01__c: null,
            phone02__c: null,
            phone03__c: null,
            phone04__c: null,
            phone05__c: null,
            phone06__c: null,
            phone07__c: null,
            phone08__c: null,
            phone09__c: null,
            phone10__c: null,
            picklist02__c: 't01,t02,t03,t04,t01,t02,t03,t04,t01,t02,t03,t04',
            picklist03__c: 'b',
            picklist04__c: 'a',
            picklist__c: 'pick01,pick02,pick03',
            rt01__c: null,
            rt02__c: null,
            txt01__c: null,
            txt02__c: null,
            txt03__c: null,
            txt04__c: null,
            txt05__c: null,
            txt06__c: null,
            txt07__c: null,
            txt08__c: null,
            txt09__c: null,
            txt10__c: null,
            url01__c: null,
            url02__c: null,
        },
        relationshipApiNames: {
            Account: 'Account',
            CreatedBy: 'User',
            LastModifiedBy: 'User',
            Owner: 'User',
        },
        avatars: {
            Account: {
                backgroundColor: '7F8DE1',
                iconUrl:
                    'https://dval-wsm.internal.salesforce.com:7443/img/icon/t4v35/standard/account_120.png',
                recordId: '001xx000003DIIxAAO',
                type: 'Theme',
            },
            CreatedBy: {
                backgroundColor: null,
                height: null,
                photoUrl: '/profilephoto/005/T',
                recordId: '005xx000001T1vNAAS',
                type: 'Photo',
                width: null,
            },
            LastModifiedBy: {
                backgroundColor: null,
                height: null,
                photoUrl: '/profilephoto/005/T',
                recordId: '005xx000001T1vNAAS',
                type: 'Photo',
                width: null,
            },
            Owner: {
                backgroundColor: null,
                height: null,
                photoUrl: '/profilephoto/005/T',
                recordId: '005xx000001T1vNAAS',
                type: 'Photo',
                width: null,
            },
        },
    },
    record: {
        apiName: 'Opportunity',
        childRelationships: {},
        fields: {
            Account: {
                displayValue: 'Acme',
                value: {
                    apiName: 'Account',
                    childRelationships: {},
                    fields: {
                        Id: {
                            displayValue: null,
                            value: '001xx000003DIIxAAO',
                        },
                        Name: {
                            displayValue: null,
                            value: 'Acme',
                        },
                    },
                    id: '001xx000003DIIxAAO',
                    recordTypeInfo: null,
                },
            },
            AccountId: {
                displayValue: null,
                value: '001xx000003DIIxAAO',
            },
            Amount: {
                displayValue: '$140,000.00',
                value: 140000,
            },
            Campaign: {
                displayValue: null,
                value: null,
            },
            CampaignId: {
                displayValue: null,
                value: null,
            },
            Checkbox10__c: {
                displayValue: null,
                value: false,
            },
            Checkbox11__c: {
                displayValue: null,
                value: false,
            },
            Checkbox12__c: {
                displayValue: null,
                value: false,
            },
            Checkbox13__c: {
                displayValue: null,
                value: false,
            },
            Checkbox14__c: {
                displayValue: null,
                value: false,
            },
            Checkbox15__c: {
                displayValue: null,
                value: false,
            },
            Checkbox16__c: {
                displayValue: null,
                value: false,
            },
            Checkbox17__c: {
                displayValue: null,
                value: false,
            },
            Checkbox18__c: {
                displayValue: null,
                value: false,
            },
            Checkbox19__c: {
                displayValue: null,
                value: false,
            },
            Checkbox1__c: {
                displayValue: null,
                value: true,
            },
            Checkbox20__c: {
                displayValue: null,
                value: false,
            },
            Checkbox2__c: {
                displayValue: null,
                value: false,
            },
            Checkbox3__c: {
                displayValue: null,
                value: false,
            },
            Checkbox4__c: {
                displayValue: null,
                value: true,
            },
            Checkbox5__c: {
                displayValue: null,
                value: false,
            },
            Checkbox6__c: {
                displayValue: null,
                value: false,
            },
            Checkbox7__c: {
                displayValue: null,
                value: false,
            },
            Checkbox8__c: {
                displayValue: null,
                value: false,
            },
            Checkbox9__c: {
                displayValue: null,
                value: false,
            },
            CloseDate: {
                displayValue: '5/5/2015',
                value: '2015-05-05',
            },
            CreatedBy: {
                displayValue: 'Test User',
                value: {
                    apiName: 'User',
                    childRelationships: {},
                    fields: {
                        Id: {
                            displayValue: null,
                            value: '005xx000001T1vNAAS',
                        },
                        Name: {
                            displayValue: null,
                            value: 'Test User',
                        },
                    },
                    id: '005xx000001T1vNAAS',
                    recordTypeInfo: null,
                },
            },
            CreatedById: {
                displayValue: null,
                value: '005xx000001T1vNAAS',
            },
            CreatedDate: {
                displayValue: '7/17/2017 1:36 PM',
                value: '2017-07-17T20:36:53.000Z',
            },
            Currency10__c: {
                displayValue: '$765',
                value: 765,
            },
            Currency11__c: {
                displayValue: '$765',
                value: 765,
            },
            Currency12__c: {
                displayValue: '$43',
                value: 43,
            },
            Currency13__c: {
                displayValue: '$6',
                value: 6,
            },
            Currency14__c: {
                displayValue: '$7,876',
                value: 7876,
            },
            Currency15__c: {
                displayValue: '$45',
                value: 45,
            },
            Currency16__c: {
                displayValue: '$4',
                value: 4,
            },
            Currency17__c: {
                displayValue: '$87',
                value: 87,
            },
            Currency18__c: {
                displayValue: '$234',
                value: 234,
            },
            Currency19__c: {
                displayValue: '$876',
                value: 876,
            },
            Currency1__c: {
                displayValue: '$876',
                value: 876,
            },
            Currency20__c: {
                displayValue: '$6',
                value: 6,
            },
            Currency2__c: {
                displayValue: '$899',
                value: 899,
            },
            Currency3__c: {
                displayValue: '$98',
                value: 98,
            },
            Currency4__c: {
                displayValue: '$98',
                value: 98,
            },
            Currency5__c: {
                displayValue: '$5',
                value: 5,
            },
            Currency7__c: {
                displayValue: '$456',
                value: 456,
            },
            Currency8__c: {
                displayValue: '$88',
                value: 88,
            },
            Currency9__c: {
                displayValue: '$87',
                value: 87,
            },
            Date10__c: {
                displayValue: null,
                value: null,
            },
            Date11__c: {
                displayValue: null,
                value: null,
            },
            Date12__c: {
                displayValue: null,
                value: null,
            },
            Date13__c: {
                displayValue: null,
                value: null,
            },
            Date14__c: {
                displayValue: null,
                value: null,
            },
            Date15__c: {
                displayValue: null,
                value: null,
            },
            Date16__c: {
                displayValue: null,
                value: null,
            },
            Date17__c: {
                displayValue: null,
                value: null,
            },
            Date18__c: {
                displayValue: null,
                value: null,
            },
            Date19__c: {
                displayValue: null,
                value: null,
            },
            Date1__c: {
                displayValue: '7/31/2017',
                value: '2017-07-31',
            },
            Date20__c: {
                displayValue: null,
                value: null,
            },
            Date5__c: {
                displayValue: null,
                value: null,
            },
            Date6__c: {
                displayValue: null,
                value: null,
            },
            Date7__c: {
                displayValue: null,
                value: null,
            },
            Date8__c: {
                displayValue: null,
                value: null,
            },
            Date9__c: {
                displayValue: null,
                value: null,
            },
            DateTime10__c: {
                displayValue: '7/18/2017 12:30 PM',
                value: '2017-07-18T19:30:00.000Z',
            },
            DateTime11__c: {
                displayValue: '7/3/2017 12:30 PM',
                value: '2017-07-03T19:30:00.000Z',
            },
            DateTime12__c: {
                displayValue: '7/19/2017 12:30 PM',
                value: '2017-07-19T19:30:00.000Z',
            },
            DateTime13__c: {
                displayValue: null,
                value: null,
            },
            DateTime14__c: {
                displayValue: '7/5/2017 12:30 PM',
                value: '2017-07-05T19:30:00.000Z',
            },
            DateTime15__c: {
                displayValue: '7/17/2017 12:30 PM',
                value: '2017-07-17T19:30:00.000Z',
            },
            DateTime16__c: {
                displayValue: null,
                value: null,
            },
            DateTime17__c: {
                displayValue: '7/2/2017 12:30 PM',
                value: '2017-07-02T19:30:00.000Z',
            },
            DateTime18__c: {
                displayValue: null,
                value: null,
            },
            DateTime19__c: {
                displayValue: '7/4/2017 12:30 PM',
                value: '2017-07-04T19:30:00.000Z',
            },
            DateTime1__c: {
                displayValue: '7/11/2017 12:30 PM',
                value: '2017-07-11T19:30:00.000Z',
            },
            DateTime20__c: {
                displayValue: null,
                value: null,
            },
            DateTime2__c: {
                displayValue: null,
                value: null,
            },
            DateTime3__c: {
                displayValue: '7/3/2017 12:30 PM',
                value: '2017-07-03T19:30:00.000Z',
            },
            DateTime4__c: {
                displayValue: null,
                value: null,
            },
            DateTime5__c: {
                displayValue: null,
                value: null,
            },
            DateTime6__c: {
                displayValue: null,
                value: null,
            },
            DateTime7__c: {
                displayValue: null,
                value: null,
            },
            DateTime8__c: {
                displayValue: null,
                value: null,
            },
            DateTime9__c: {
                displayValue: null,
                value: null,
            },
            Description: {
                displayValue: null,
                value:
                    'The deal is at  50% because they are at the sales process stage of evaluating our ROI justification.',
            },
            Email10__c: {
                displayValue: null,
                value: 'foo@bar.com',
            },
            Email11__c: {
                displayValue: null,
                value: 'foo@bar.com',
            },
            Email12__c: {
                displayValue: null,
                value: 'foo@bar.com',
            },
            Email13__c: {
                displayValue: null,
                value: 'foo@bar.com',
            },
            Email14__c: {
                displayValue: null,
                value: 'foo@bar.com',
            },
            Email15__c: {
                displayValue: null,
                value: 'foo@bar.com',
            },
            Email16__c: {
                displayValue: null,
                value: 'foo@bar.com',
            },
            Email17__c: {
                displayValue: null,
                value: 'foo@bar.com',
            },
            Email18__c: {
                displayValue: null,
                value: 'foo@bar.com',
            },
            Email19__c: {
                displayValue: null,
                value: 'foo@bar.comv',
            },
            Email1__c: {
                displayValue: null,
                value: 'foo@bar.com',
            },
            Email20__c: {
                displayValue: null,
                value: 'foo@bar.com',
            },
            Email2__c: {
                displayValue: null,
                value: 'foo@bar.com',
            },
            Email3__c: {
                displayValue: null,
                value: 'foo@bar.com',
            },
            Email4__c: {
                displayValue: null,
                value: 'foo@bar.com',
            },
            Email5__c: {
                displayValue: null,
                value: 'foo@bar.com',
            },
            Email6__c: {
                displayValue: null,
                value: 'foo@bar.com',
            },
            Email7__c: {
                displayValue: null,
                value: 'foo@bar.com',
            },
            Email8__c: {
                displayValue: null,
                value: 'foo@bar.com',
            },
            Email9__c: {
                displayValue: null,
                value: 'foo@bar.com',
            },
            ForecastCategoryName: {
                displayValue: 'Pipeline',
                value: 'Pipeline',
            },
            LastModifiedBy: {
                displayValue: 'Test User',
                value: {
                    apiName: 'User',
                    childRelationships: {},
                    fields: {
                        Id: {
                            displayValue: null,
                            value: '005xx000001T1vNAAS',
                        },
                        Name: {
                            displayValue: null,
                            value: 'Test User',
                        },
                    },
                    id: '005xx000001T1vNAAS',
                    recordTypeInfo: null,
                },
            },
            LastModifiedById: {
                displayValue: null,
                value: '005xx000001T1vNAAS',
            },
            LastModifiedDate: {
                displayValue: '7/21/2017 12:32 PM',
                value: '2017-07-21T19:32:11.000Z',
            },
            LeadSource: {
                displayValue: 'Trade Show',
                value: 'Trade Show',
            },
            Name: {
                displayValue: null,
                value: 'Acme - 1,200 Widgets',
            },
            NextStep: {
                displayValue: null,
                value: 'Need estimate',
            },
            Num10__c: {
                displayValue: null,
                value: 876,
            },
            Num11__c: {
                displayValue: null,
                value: 87,
            },
            Num12__c: {
                displayValue: null,
                value: 65,
            },
            Num13__c: {
                displayValue: null,
                value: 68,
            },
            Num14__c: {
                displayValue: null,
                value: 876,
            },
            Num15__c: {
                displayValue: null,
                value: 123,
            },
            Num16__c: {
                displayValue: null,
                value: 765,
            },
            Num17__c: {
                displayValue: null,
                value: 65,
            },
            Num18__c: {
                displayValue: null,
                value: null,
            },
            Num19__c: {
                displayValue: null,
                value: null,
            },
            Num1__c: {
                displayValue: null,
                value: 76,
            },
            Num20__c: {
                displayValue: null,
                value: 5,
            },
            Num2__c: {
                displayValue: null,
                value: 87,
            },
            Num3__c: {
                displayValue: null,
                value: 876,
            },
            Num4__c: {
                displayValue: null,
                value: 876,
            },
            Num5__c: {
                displayValue: null,
                value: 5,
            },
            Num6__c: {
                displayValue: null,
                value: 5,
            },
            Num7__c: {
                displayValue: null,
                value: 7865,
            },
            Num8__c: {
                displayValue: null,
                value: 7865,
            },
            Num9__c: {
                displayValue: null,
                value: 86,
            },
            Owner: {
                displayValue: 'Test User',
                value: {
                    apiName: 'User',
                    childRelationships: {},
                    fields: {
                        Id: {
                            displayValue: null,
                            value: '005xx000001T1vNAAS',
                        },
                        Name: {
                            displayValue: null,
                            value: 'Test User',
                        },
                    },
                    id: '005xx000001T1vNAAS',
                    recordTypeInfo: null,
                },
            },
            OwnerId: {
                displayValue: null,
                value: '005xx000001T1vNAAS',
            },
            Perc10__c: {
                displayValue: null,
                value: 4,
            },
            Perc11__c: {
                displayValue: null,
                value: 6,
            },
            Perc12__c: {
                displayValue: null,
                value: 123,
            },
            Perc13__c: {
                displayValue: null,
                value: 123,
            },
            Perc14__c: {
                displayValue: null,
                value: 5,
            },
            Perc15__c: {
                displayValue: null,
                value: 6,
            },
            Perc16__c: {
                displayValue: null,
                value: 123,
            },
            Perc17__c: {
                displayValue: null,
                value: 123,
            },
            Perc18__c: {
                displayValue: null,
                value: 5,
            },
            Perc19__c: {
                displayValue: null,
                value: 8,
            },
            Perc1__c: {
                displayValue: null,
                value: 122,
            },
            Perc20__c: {
                displayValue: null,
                value: 2,
            },
            Perc2__c: {
                displayValue: null,
                value: 2,
            },
            Perc3__c: {
                displayValue: null,
                value: 9,
            },
            Perc4__c: {
                displayValue: null,
                value: 9,
            },
            Perc5__c: {
                displayValue: null,
                value: 6,
            },
            Perc6__c: {
                displayValue: null,
                value: 7,
            },
            Perc7__c: {
                displayValue: null,
                value: 7,
            },
            Perc8__c: {
                displayValue: null,
                value: 6,
            },
            Perc9__c: {
                displayValue: null,
                value: 5,
            },
            Phone11__c: {
                displayValue: null,
                value: '65',
            },
            Phone12__c: {
                displayValue: null,
                value: '87',
            },
            Phone13__c: {
                displayValue: null,
                value: '876',
            },
            Phone14__c: {
                displayValue: null,
                value: '587',
            },
            Phone15__c: {
                displayValue: null,
                value: '5',
            },
            Phone16__c: {
                displayValue: null,
                value: '876',
            },
            Phone17__c: {
                displayValue: null,
                value: '65',
            },
            Phone18__c: {
                displayValue: null,
                value: '8765',
            },
            Phone19__c: {
                displayValue: null,
                value: '876',
            },
            Phone20__c: {
                displayValue: null,
                value: '876',
            },
            Phone2__c: {
                displayValue: null,
                value: '5',
            },
            Phone3__c: {
                displayValue: null,
                value: '765',
            },
            Phone4__c: {
                displayValue: null,
                value: '58',
            },
            Phone5__c: {
                displayValue: null,
                value: '587',
            },
            Phone6__c: {
                displayValue: null,
                value: '876',
            },
            Phone7__c: {
                displayValue: null,
                value: '765',
            },
            Phone8__c: {
                displayValue: null,
                value: '65',
            },
            Phone9__c: {
                displayValue: null,
                value: '876',
            },
            Pricebook2: {
                displayValue: null,
                value: null,
            },
            Pricebook2Id: {
                displayValue: null,
                value: null,
            },
            Probability: {
                displayValue: null,
                value: 50,
            },
            StageName: {
                displayValue: 'Value Proposition',
                value: 'Value Proposition',
            },
            Text18__c: {
                displayValue: null,
                value: 'foo',
            },
            Text19__c: {
                displayValue: null,
                value: 'gkj',
            },
            Text1__c: {
                displayValue: null,
                value: 'is',
            },
            Text20__c: {
                displayValue: null,
                value: 'hjg',
            },
            Text2__c: {
                displayValue: null,
                value: 'garbage',
            },
            Text3__c: {
                displayValue: null,
                value: 'stuff',
            },
            Text4__c: {
                displayValue: null,
                value: 'for',
            },
            Text5__c: {
                displayValue: null,
                value: 'recprd',
            },
            Text8__c: {
                displayValue: null,
                value: 'kjh',
            },
            Text9__c: {
                displayValue: null,
                value: 'hg',
            },
            TextArea10__c: {
                displayValue: null,
                value: 'kgv',
            },
            TextArea11__c: {
                displayValue: null,
                value: 'hg',
            },
            TextArea12__c: {
                displayValue: null,
                value: 'kj',
            },
            TextArea13__c: {
                displayValue: null,
                value: 'jkh',
            },
            TextArea14__c: {
                displayValue: null,
                value: 'kj',
            },
            TextArea15__c: {
                displayValue: null,
                value: 'gkj',
            },
            TextArea16__c: {
                displayValue: null,
                value: 'hg',
            },
            TextArea17__c: {
                displayValue: null,
                value: 'hj',
            },
            TextArea18__c: {
                displayValue: null,
                value: 'kjhg',
            },
            TextArea19__c: {
                displayValue: null,
                value: 'hg',
            },
            TextArea1__c: {
                displayValue: null,
                value: 'asd',
            },
            TextArea20__c: {
                displayValue: null,
                value: 'kj',
            },
            TextArea2__c: {
                displayValue: null,
                value: 'vh',
            },
            TextArea3__c: {
                displayValue: null,
                value: 'kjh',
            },
            TextArea4__c: {
                displayValue: null,
                value: 'gv',
            },
            TextArea5__c: {
                displayValue: null,
                value: 'hg',
            },
            TextArea6__c: {
                displayValue: null,
                value: 'kjh',
            },
            TextArea7__c: {
                displayValue: null,
                value: 'khg',
            },
            TextArea8__c: {
                displayValue: null,
                value: 'gkj',
            },
            TextArea9__c: {
                displayValue: null,
                value: 'jgv',
            },
            Type: {
                displayValue: 'Existing Business',
                value: 'Existing Business',
            },
            c01__c: {
                displayValue: '$12',
                value: 12,
            },
            c02__c: {
                displayValue: '$123',
                value: 123,
            },
            c03__c: {
                displayValue: '$123',
                value: 123,
            },
            c04__c: {
                displayValue: '$123',
                value: 123,
            },
            c05__c: {
                displayValue: '7/2/2017',
                value: '2017-07-02',
            },
            date01__c: {
                displayValue: '7/15/2017',
                value: '2017-07-15',
            },
            date02__c: {
                displayValue: '7/3/2017',
                value: '2017-07-03',
            },
            date03__c: {
                displayValue: '7/10/2017',
                value: '2017-07-10',
            },
            date04__c: {
                displayValue: '7/10/2017',
                value: '2017-07-10',
            },
            date05__c: {
                displayValue: '7/3/2017',
                value: '2017-07-03',
            },
            dt01__c: {
                displayValue: '7/13/2017 3:17 PM',
                value: '2017-07-13T22:17:00.000Z',
            },
            dt02__c: {
                displayValue: '7/4/2017 3:17 PM',
                value: '2017-07-04T22:17:00.000Z',
            },
            dt03__c: {
                displayValue: '7/20/2017 3:17 PM',
                value: '2017-07-20T22:17:00.000Z',
            },
            dt04__c: {
                displayValue: '6/28/2017 3:17 PM',
                value: '2017-06-28T22:17:00.000Z',
            },
            dt05__c: {
                displayValue: '7/7/2017 3:17 PM',
                value: '2017-07-07T22:17:00.000Z',
            },
            dt06__c: {
                displayValue: '7/22/2017 3:17 PM',
                value: '2017-07-22T22:17:00.000Z',
            },
            dt07__c: {
                displayValue: '7/16/2017 3:17 PM',
                value: '2017-07-16T22:17:00.000Z',
            },
            dt08__c: {
                displayValue: '7/3/2017 6:42 PM',
                value: '2017-07-04T01:42:00.000Z',
            },
            dt09__c: {
                displayValue: '6/26/2017 6:42 PM',
                value: '2017-06-27T01:42:00.000Z',
            },
            dt10__c: {
                displayValue: '7/10/2017 3:17 PM',
                value: '2017-07-10T22:17:00.000Z',
            },
            e01__c: {
                displayValue: null,
                value: 'foo@bar.com',
            },
            e02__c: {
                displayValue: null,
                value: 'foo@bar.com',
            },
            e03__c: {
                displayValue: null,
                value: 'foo@bar.com',
            },
            e04__c: {
                displayValue: null,
                value: 'foo@bar.com',
            },
            e05__c: {
                displayValue: null,
                value: 'foo@bar.com',
            },
            e06__c: {
                displayValue: null,
                value: 'foo@bar.com',
            },
            e07__c: {
                displayValue: null,
                value: 'foo@bar.com',
            },
            e08__c: {
                displayValue: null,
                value: 'foo@bar.com',
            },
            e09__c: {
                displayValue: null,
                value: 'foo@bar.com',
            },
            e10__c: {
                displayValue: null,
                value: 'foo@bar.com',
            },
            n01__c: {
                displayValue: null,
                value: 123,
            },
            n02__c: {
                displayValue: null,
                value: 120,
            },
            n03__c: {
                displayValue: null,
                value: 786234876,
            },
            n04__c: {
                displayValue: null,
                value: 387623,
            },
            n05__c: {
                displayValue: null,
                value: 28765,
            },
            n06__c: {
                displayValue: null,
                value: 123213423,
            },
            n07__c: {
                displayValue: null,
                value: 23423234,
            },
            n08__c: {
                displayValue: null,
                value: 12457,
            },
            n09__c: {
                displayValue: null,
                value: 245769,
            },
            n10__c: {
                displayValue: null,
                value: 234275,
            },
            percent01__c: {
                displayValue: null,
                value: 12,
            },
            percent02__c: {
                displayValue: null,
                value: 345,
            },
            percent03__c: {
                displayValue: null,
                value: 12,
            },
            percent04__c: {
                displayValue: null,
                value: 345,
            },
            percent05__c: {
                displayValue: null,
                value: 23,
            },
            percent06__c: {
                displayValue: null,
                value: 123,
            },
            percent07__c: {
                displayValue: null,
                value: 2,
            },
            percent09__c: {
                displayValue: null,
                value: 123,
            },
            percent8__c: {
                displayValue: null,
                value: 3,
            },
            phone01__c: {
                displayValue: null,
                value: '34',
            },
            phone02__c: {
                displayValue: null,
                value: '5',
            },
            phone03__c: {
                displayValue: null,
                value: '55',
            },
            phone04__c: {
                displayValue: null,
                value: '123',
            },
            phone05__c: {
                displayValue: null,
                value: '35',
            },
            phone06__c: {
                displayValue: null,
                value: '1234',
            },
            phone07__c: {
                displayValue: null,
                value: '54',
            },
            phone08__c: {
                displayValue: null,
                value: '123',
            },
            phone09__c: {
                displayValue: null,
                value: '32',
            },
            phone10__c: {
                displayValue: null,
                value: 's2e234',
            },
            picklist02__c: {
                displayValue: 't01,t02,t03,t04,t01,t02,t03,t04,t01,t02,t03,t04',
                value: 't01,t02,t03,t04,t01,t02,t03,t04,t01,t02,t03,t04',
            },
            picklist03__c: {
                displayValue: 'b',
                value: 'b',
            },
            picklist04__c: {
                displayValue: 'a',
                value: 'a',
            },
            picklist__c: {
                displayValue: 'pick01,pick02,pick03',
                value: 'pick01,pick02,pick03',
            },
            rt01__c: {
                displayValue: null,
                value:
                    '&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;',
            },
            rt02__c: {
                displayValue: null,
                value:
                    '&quot;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&quot;',
            },
            txt01__c: {
                displayValue: null,
                value: 'asd',
            },
            txt02__c: {
                displayValue: null,
                value: 'sdf',
            },
            txt03__c: {
                displayValue: null,
                value: 'sdf',
            },
            txt04__c: {
                displayValue: null,
                value: 'sdf',
            },
            txt05__c: {
                displayValue: null,
                value: 'sdf',
            },
            txt06__c: {
                displayValue: null,
                value: 'sdf',
            },
            txt07__c: {
                displayValue: null,
                value: 'sdf',
            },
            txt08__c: {
                displayValue: null,
                value: 'sdf',
            },
            txt09__c: {
                displayValue: null,
                value: 'sdf',
            },
            txt10__c: {
                displayValue: null,
                value: 'dsfsdf',
            },
            url01__c: {
                displayValue: null,
                value: 'foo.com',
            },
            url02__c: {
                displayValue: null,
                value: 'qsd',
            },
        },
        id: '006xx000001ZdxuAAC',
        recordTypeInfo: null,
    },
    sections: {
        id_01Bxx0000029W6VEAU: {
            isCollapsed: false,
        },
        id_01Bxx0000029W7NEAU: {
            isCollapsed: false,
        },
    },
};
