import sValue from './helpers/some.js';

export default class Bar {
    constructor(attrs) {
        this.a = attrs.a;
        this.b = attrs.b || sValue;
        this.foo = [ { x: 1 }, { x: 2 } ];
    }
    get x() {
        return this.b + 1;
    }
    get c() {
        return this.a + this.b;
    }
    onClick() {
        this.a += 1;
        this.a.y.z = 2;
        this.b += '.';
        console.log('clicked');
    }

    attach(domNode) {
        console.log('attaching ', domNode);
    }

    ditach(domNode) {
        console.log('detaching ', domNode);
    }

    // after this line, all code is generated by the build process
    // this is a generated method based on the template
    render({f,h,t,i}) {
        const iter1 = (item) => {
            return h('li', {
                a: item.x
            }, ['iterator', this.b]);
        };
        return h('button', {
            name: this.a,
            'onClick.call': 'onClick',
        }, [
            h('span', {}, [
                t(this.b),
            ]),
            this.a ? h('span', {}, ['something']) : f(),
            h('ul', {}, [
                h('li', {}, ['first']),
                i(this.foo, iter1),
                h('li', {}, ['last']),
            ])
        ]);
    }
}

// <Bar a.bind="x" />
