import baseConfig from './base.mjs';
import testPlugin from './plugins/serve-integration.mjs';

/** @type {import("@web/test-runner").TestRunnerConfig} */
export default {
    ...baseConfig,
    files: [
        // FIXME: These tests are just symlinks to integration-karma for now so the git diff smaller
        'test/**/*.spec.js',
        // Failing Karma tests that need to be migrated to WTR
        '!test/accessibility/synthetic-cross-root-aria/index.spec.js',
        '!test/api/CustomElementConstructor-getter/index.spec.js',
        '!test/api/freezeTemplate/index.spec.js',
        '!test/api/getComponentDef/index.spec.js',
        '!test/api/isNodeFromTemplate/index.spec.js',
        '!test/api/registerTemplate/index.spec.js',
        '!test/api/sanitizeAttribute/index.spec.js',
        '!test/api/sanitizeHtmlContent/index.spec.js',
        '!test/component/face-callbacks/index.spec.js',
        '!test/component/LightningElement.addEventListener/index.spec.js',
        '!test/component/LightningElement.attachInternals/api/index.spec.js',
        '!test/component/LightningElement.connectedCallback/index.spec.js',
        '!test/component/LightningElement.errorCallback/index.spec.js',
        '!test/component/LightningElement.render/index.spec.js',
        '!test/component/LightningElement/index.spec.js',
        '!test/component/native-vs-synthetic-lifecycle/index.spec.js',
        '!test/custom-elements-registry/index.spec.js',
        '!test/events/focus-event-related-target/index.spec.js',
        '!test/integrations/locker/index.spec.js',
        '!test/light-dom/host-pseudo/index.spec.js',
        '!test/light-dom/multiple-templates/index.spec.js',
        '!test/light-dom/scoped-slot/if-block/index.spec.js',
        '!test/light-dom/scoped-styles/index.spec.js',
        '!test/light-dom/slot-fowarding/slots/duplicates/index.spec.js',
        '!test/light-dom/style-global/index.spec.js',
        '!test/lwc-on/index.spec.js',
        '!test/misc/clean-dom/index.spec.js',
        '!test/mixed-shadow-mode/composed-path/index.spec.js',
        '!test/polyfills/document-body-properties/index.spec.js',
        '!test/polyfills/document-properties/index.spec.js',
        '!test/profiler/mutation-logging/index.spec.js',
        '!test/regression/invalid-key/index.spec.js',
        '!test/rendering/callback-invocation-order/index.spec.js',
        '!test/rendering/iframe/index.spec.js',
        '!test/rendering/inner-outer-html/index.spec.js',
        '!test/rendering/legacy-stylesheet-api/index.spec.js',
        '!test/rendering/sanitize-stylesheet-token/index.spec.js',
        '!test/rendering/side-effects/index.spec.js',
        '!test/rendering/slotting/index.spec.js',
        '!test/rendering/stylesheet-caching/index.spec.js',
        '!test/rendering/version-mismatch/index.spec.js',
        '!test/shadow-dom/Element-properties/index.spec.js',
        '!test/shadow-dom/Event-properties/Event.target.spec.js',
        '!test/shadow-dom/multiple-templates/index.spec.js',
        '!test/shadow-dom/Node-properties/Node.getRootNode.spec.js',
        '!test/shadow-dom/ShadowRoot.elementsFromPoint/index.spec.js',
        '!test/signal/protocol/index.spec.js',
        '!test/spread/index.spec.js',
        '!test/swapping/styles/index.spec.js',
        '!test/synthetic-shadow/dom-manual-sharing-nodes/index.spec.js',
        '!test/synthetic-shadow/element-api/element-api.spec.js',
        '!test/synthetic-shadow/host-pseudo/index.spec.js',
        '!test/template/directive-for-each/index.spec.js',
        '!test/template/directive-lwc-render-mode/index.spec.js',
    ],
    plugins: [...baseConfig.plugins, testPlugin],
};
