import * as path from "path";
import compile from "lwc-template-compiler";

import { CompilerError } from "../common-interfaces/compiler-error";
import { NormalizedCompilerOptions } from "../compiler/options";
import { FileTransformer } from "./transformer";

// TODO: once we come up with a strategy to export all types from the module,
// below interface should be removed and resolved from template-compiler module.
export interface TemplateMetadata {
    templateUsedIds: string[];
    definedSlots: string[];
    templateDependencies: string[];
}

function attachStyleToTemplate(
    src: string,
    filename: string,
) {
    console.log('---- pre file reading');
    const templateFilename = path.basename(filename, path.extname(filename));
    console.log('---- post file reading: ', templateFilename);
    const result = [
        `import stylesheet from './${templateFilename}.css'`,
        "",
        src,
        "",

        // The compiler resolves the style import to undefined if the stylesheet
        // doesn't exists.
        `if (stylesheet) {`,

        // hostToken and shadowToken are generated by the style transform
        // * `hostToken`: is applied only to the host element
        // * `shadowToken`: is applied to all the element generated by the template
        `    tmpl.hostToken = stylesheet.hostToken;`,
        `    tmpl.shadowToken = stylesheet.shadowToken;`,
        ``,

        // Inject the component style in a new style tag the document head.
        `    const style = document.createElement('style');`,
        `    style.type = 'text/css';`,
        `    style.dataset.token = stylesheet.shadowToken`,
        `    style.textContent = stylesheet.content`,
        `    document.head.appendChild(style);`,
        `}`
    ].join("\n");

    return result;
}

/**
 * Transforms a HTML template into module exporting a template function.
 * The transform also add a style import for the default stylesheet associated with
 * the template regardless if there is an actual style or not.
 */
const transform: FileTransformer = function(
    src: string,
    filename: string,
    options: NormalizedCompilerOptions
) {

    let code;
    let metadata;

    try {
        const result = compile(src, {});
        const warnings = result.warnings;

        code = result.code;
        metadata = result.metadata;

        const fatalError = warnings.find(warning => warning.level === "error");
        if (fatalError) {
            throw new CompilerError(`${filename}: ${fatalError.message}`, filename);
        }
    } catch (e) {
        throw new CompilerError(e.message, filename, e.loc);
    }

    return {
        code: attachStyleToTemplate(code, filename),
        metadata,
        map: null
    };
};

export default transform;
