import * as path from "path";
import compile from "lwc-template-compiler";

import { CompilerError } from "../common-interfaces/compiler-error";
import { NormalizedCompilerOptions } from "../compiler/options";
import { FileTransformer } from "./transformer";

const DEFAULT_NAMESPACE = "c";

// TODO: once we come up with a strategy to export all types from the module,
// below interface should be removed and resolved from template-compiler module.
export interface TemplateMetadata {
    templateUsedIds: string[];
    definedSlots: string[];
    templateDependencies: string[];
}

function attachStyleToTemplate(
    src: string,
    filename: string,
    options: NormalizedCompilerOptions
) {
    const { name } = options;

    // if namespace is not specified normalize to 'c'
    const namespace = normalizedNamespace(options.namespace);

    const templateFilename = path.basename(filename, path.extname(filename));

    // Use the component tagname and a unique style token to scope the compiled
    // styles to the component.
    const tagName = `${namespace}-${name}`;
    const shadowToken = `${tagName}_${templateFilename}`;
    const hostToken = `${shadowToken}-host`;

    return [
        `import stylesheet from './${templateFilename}.css'`,
        "",
        src,
        "",

        // The compiler resolves the style import to undefined if the stylesheet
        // doesn't exists.
        `if (stylesheet) {`,

        // The engine picks the tokens from the template during rendering:
        // * `hostToken`: is applied only to the host element
        // * `shadowToken`: is applied to all the element generated by the template
        `    tmpl.hostToken = '${hostToken}';`,
        `    tmpl.shadowToken = '${shadowToken}';`,
        ``,

        // Inject the component style in a new style tag the document head.
        `    const style = document.createElement('style');`,
        `    style.type = 'text/css';`,
        `    style.dataset.token = '${shadowToken}'`,
        `    style.textContent = stylesheet('${shadowToken}');`,
        `    document.head.appendChild(style);`,
        `}`
    ].join("\n");
}

function normalizedNamespace(namespace: string | undefined) {
    return namespace && namespace.length ? namespace : DEFAULT_NAMESPACE;
}

/**
 * Transforms a HTML template into module exporting a template function.
 * The transform also add a style import for the default stylesheet associated with
 * the template regardless if there is an actual style or not.
 */
const transform: FileTransformer = function(
    src: string,
    filename: string,
    options: NormalizedCompilerOptions
) {
    let code;
    let metadata;

    try {
        // if namespace is not specified normalize to 'c'
        const namespace = normalizedNamespace(options.namespace);
        const result = compile(src, { namespace });
        const warnings = result.warnings;

        code = result.code;
        metadata = result.metadata;

        const fatalError = warnings.find(warning => warning.level === "error");
        if (fatalError) {
            throw new CompilerError(
                `${filename}: ${fatalError.message}`,
                filename
            );
        }
    } catch (e) {
        throw new CompilerError(e.message, filename, e.loc);
    }

    return {
        code: attachStyleToTemplate(code, filename, options),
        metadata,
        map: null
    };
};

export default transform;
