name: Run Best benchmark

on: push

env:
  BEST_FRONTEND_CLIENT_TOKEN: ${{secrets.BEST_FRONTEND_CLIENT_TOKEN}}
  BEST_FRONTEND_HOSTNAME: ${{secrets.BEST_FRONTEND_HOSTNAME}}
  BEST_HUB_CLIENT_TOKEN: ${{secrets.BEST_HUB_CLIENT_TOKEN}}
  BEST_HUB_HOSTNAME: ${{secrets.BEST_HUB_HOSTNAME}}

jobs:
  run-best-performance-tests:
    runs-on: salesforce-Ubuntu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      # TODO: remove this debugging step
      - name: IP
        run: curl https://checkip.amazonaws.com/

      - name: curl best hub
        run: curl ${{secrets.BEST_HUB_HOSTNAME}}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build benchmarks
        run: yarn build:performance

      - name: Run benchmarks
        run: yarn test:performance:best --runner remote
