name: Run WebDriverIO integration tests

on:
    push:
        branches:
            - master
            - release
            - 'spring*'
            - 'summer*'
            - 'winter*'
    pull_request:
        branches:
            - master
            - release
            - 'spring*'
            - 'summer*'
            - 'winter*'

env:
    PUPPETEER_SKIP_DOWNLOAD: 'true' # only needed for @best/runner-local, unused here
    CHROMEDRIVER_BINARY: '../../../node_modules/chromedriver/lib/chromedriver/chromedriver' # pin wdio to local chromedriver

jobs:
    run-integration-tests:
        runs-on: ubuntu-22.04
        defaults:
            run:
                working-directory: ./packages/@lwc/integration-tests
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: '20.12.2'
                  cache: 'yarn'

            # Needed for local browser integration tests
            # chrome-version documentation can be found here: https://github.com/browser-actions/setup-chrome?tab=readme-ov-file#usage
            - name: Setup chrome v124
              uses: browser-actions/setup-chrome@v1
              with:
                  chrome-version: 124
              id: setup-chrome

            - name: Install dependencies
              run: yarn install --frozen-lockfile
              working-directory: ./

            # Pin chromedriver to the same version as Chrome above
            - name: Install chromedriver v124
              run: yarn add -W chromedriver@^124
              working-directory: ./

            - run: CHROME_BINARY=${{ steps.setup-chrome.outputs.chrome-path }} yarn local:prod
            - run: CHROME_BINARY=${{ steps.setup-chrome.outputs.chrome-path }} yarn local:dev
