name: Run WebDriverIO integration tests

on:
    push:
        branches:
            - master
            - release
            - 'spring*'
            - 'summer*'
            - 'winter*'
    pull_request:
        branches:
            - master
            - release
            - 'spring*'
            - 'summer*'
            - 'winter*'

env:
    PUPPETEER_SKIP_DOWNLOAD: 'true' # only needed for @best/runner-local, unused here

jobs:
    run-integration-tests:
        runs-on: ubuntu-22.04
        defaults:
            run:
                working-directory: ./packages/@lwc/integration-tests
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: '20.12.2'
                  cache: 'yarn'

            - name: Install dependencies
              run: yarn install --frozen-lockfile
              working-directory: ./

            - run: yarn local:prod
            - run: yarn local:dev
