name: Run WebDriverIO integration tests

on:
    push:
        branches:
            - master
            - release
            - 'spring*'
            - 'summer*'
            - 'winter*'
    pull_request:
        branches:
            - master
            - release
            - 'spring*'
            - 'summer*'
            - 'winter*'

env:
    PUPPETEER_SKIP_DOWNLOAD: 'true' # only needed for @best/runner-local, unused here
    CHROME_VERSION: 130

jobs:
    run-integration-tests:
        runs-on: ubuntu-22.04
        defaults:
            run:
                working-directory: ./packages/@lwc/integration-tests
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Setup Node
              uses: actions/setup-node@v6
              with:
                  node-version: '20.19.4'
                  cache: 'yarn'

            # Needed for local browser integration tests
            # chrome-version documentation can be found here: https://github.com/browser-actions/setup-chrome?tab=readme-ov-file#usage
            - name: Setup Chrome
              uses: browser-actions/setup-chrome@v2
              with:
                  chrome-version: ${{ env.CHROME_VERSION }}
              id: setup-chrome

            - name: Install dependencies
              run: yarn install --frozen-lockfile
              working-directory: ./

            # Pin chromedriver to the same version as Chrome above
            - name: Install chromedriver
              id: install-chromedriver
              run: |
                  yarn add -W chromedriver@^${{ env.CHROME_VERSION }} --ignore-scripts # Don't need to re-build
                  echo "chromedriver-path=\"$(yarn bin chromedriver)\"" >> "$GITHUB_OUTPUT"
              working-directory: ./

            - run: yarn local:prod:ci
              env:
                  CHROME_BINARY: ${{ steps.setup-chrome.outputs.chrome-path }}
                  CHROMEDRIVER_BINARY: ${{ steps.install-chromedriver.outputs.chromedriver-path}}
            - run: yarn local:dev:ci
              env:
                  CHROME_BINARY: ${{ steps.setup-chrome.outputs.chrome-path }}
                  CHROMEDRIVER_BINARY: ${{ steps.install-chromedriver.outputs.chromedriver-path}}
